name: QA Table Sum Check

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install playwright

      - name: Run QA scrape script (24ds3000018@ds.study.iitm.ac.in)
        run: node scrape-and-sum.js
